// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerSideIII.Data;

#nullable disable

namespace ServerSideIII.Migrations.Todo
{
    [DbContext(typeof(TodoContext))]
    [Migration("20250902133416_InitApplication")]
    partial class InitApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerSideIII.Data.Cpr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Cpr", (string)null);
                });

            modelBuilder.Entity("ServerSideIII.Data.Todolist", b =>
                {
                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Int"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Int");

                    b.HasIndex("UserId");

                    b.ToTable("Todolist", (string)null);
                });

            modelBuilder.Entity("ServerSideIII.Data.Todolist", b =>
                {
                    b.HasOne("ServerSideIII.Data.Cpr", "User")
                        .WithMany("Todolists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Todolist_Cpr");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServerSideIII.Data.Cpr", b =>
                {
                    b.Navigation("Todolists");
                });
#pragma warning restore 612, 618
        }
    }
}
